# Generated by Django 3.1 on 2020-08-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
